import React from 'react';
import { FadeIn } from "@/components/common/FadeIn";
import { BookOpen, Layers, Network } from "lucide-react";

export const WhatWeAreNot = () => {
  return (
    <section className="py-16 md:py-20 bg-surface-50 border-t border-stone-100">
      <div className="container mx-auto px-6 max-w-6xl">
        <div className="text-center mb-10">
          <FadeIn>
            <h2 className="text-4xl md:text-5xl font-medium tracking-tight text-pine-900 mb-6">
              Three layers. <span className="text-pine-600">One connected system.</span>
            </h2>
            <p className="text-lg text-dim-2 max-w-2xl mx-auto font-medium">
              Every piece of FettleMed is designed to work together, so nothing gets lost between the patient, the doctor, and the clinic.
            </p>
          </FadeIn>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          <FadeIn delay={0.1}>
            <div className="bg-white p-7 rounded-2xl border border-stone-200 h-full shadow-sm hover:shadow-md transition-shadow">
              <div className="w-11 h-11 bg-pine-50 text-pine-700 rounded-xl flex items-center justify-center mb-5 border border-pine-100">
                <BookOpen className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-medium text-pine-900 mb-3 tracking-tight">Living Health Timeline</h3>
              <ul className="space-y-2.5 text-dim-2 font-medium text-sm">
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>No digging through WhatsApp forwards, paper folders, or memory</li>
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>Every result, diagnosis, and prescription in one place, in order</li>
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>Walk into any consultation with your full history already there</li>
              </ul>
            </div>
          </FadeIn>

          <FadeIn delay={0.2}>
            <div className="bg-white p-7 rounded-2xl border border-stone-200 h-full shadow-sm hover:shadow-md transition-shadow">
              <div className="w-11 h-11 bg-pine-50 text-pine-700 rounded-xl flex items-center justify-center mb-5 border border-pine-100">
                <Layers className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-medium text-pine-900 mb-3 tracking-tight">Built on National Standards</h3>
              <ul className="space-y-2.5 text-dim-2 font-medium text-sm">
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>Built on the ABDM framework and ABHA ID infrastructure</li>
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>The same national standards India's healthcare system is moving toward</li>
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>Compliance is not an add-on. It is the architecture.</li>
              </ul>
            </div>
          </FadeIn>

          <FadeIn delay={0.3}>
            <div className="bg-white p-7 rounded-2xl border border-stone-200 h-full shadow-sm hover:shadow-md transition-shadow md:col-span-2 lg:col-span-1">
              <div className="w-11 h-11 bg-pine-50 text-pine-700 rounded-xl flex items-center justify-center mb-5 border border-pine-100">
                <Network className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-medium text-pine-900 mb-3 tracking-tight">Connected at Every Step</h3>
              <ul className="space-y-2.5 text-dim-2 font-medium text-sm">
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>Prescription generated by the doctor appears in the patient's app instantly</li>
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>Follow-up results uploaded by the patient, visible to the clinic without another visit</li>
                <li className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-pine-500 mt-1.5 shrink-0"></span>New FettleMed patients walk in as known patients, not strangers</li>
              </ul>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>
  );
};
